#!/bin/bash
# =============================================================================
# Arch Linux Mirror Server Hardening Script
# Run after arch-mirror-setup.sh
# Covers: firewall (nftables), SSH brute-force (sshguard),
#         SSH config hardening, nginx rate limiting, auto-security-updates
# =============================================================================

set -euo pipefail

echo "========================================================"
echo "    Arch Linux Mirror Server Hardening"
echo "========================================================"

# ── Prerequisites ─────────────────────────────────────────────────────────────

# Abort if not root
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: Run as root." >&2
    exit 1
fi

# Detect SSH port from current config before we lock anything down
SSH_PORT=$(sshd -T 2>/dev/null | awk '/^port / {print $2; exit}')
SSH_PORT=${SSH_PORT:-22}
echo "Detected SSH port: $SSH_PORT"

# ── Packages ──────────────────────────────────────────────────────────────────

echo "Installing hardening packages..."
pacman -S --noconfirm --needed nftables sshguard

# ── 1. nftables Firewall ──────────────────────────────────────────────────────
# Policy: default DROP on input/forward, ACCEPT on output.
# Allowed inbound: loopback, established/related, ICMP (limited),
#                  SSH (rate-limited at firewall level too), HTTP, HTTPS.
# sshguard manages its own nftables set (sshguard4 / sshguard6) — we
# reference those sets here so bans are enforced at the kernel level,
# not in userspace.

echo "Configuring nftables..."
cat > /etc/nftables.conf <<EOF
#!/usr/bin/nft -f
# Arch Linux mirror server firewall
# Generated by arch-mirror-harden.sh

flush ruleset

table inet filter {

    # sshguard populates these sets with banned IPs.
    # Define them here so sshguard can add to them at startup.
    set sshguard4 {
        type ipv4_addr
        flags interval
    }

    set sshguard6 {
        type ipv6_addr
        flags interval
    }

    chain input {
        type filter hook input priority filter; policy drop;

        # Loopback always allowed
        iifname lo accept

        # Drop invalid state early
        ct state invalid drop

        # Allow established/related (stateful)
        ct state { established, related } accept

        # ICMP — rate-limited. Dropping all ICMP breaks path MTU discovery
        # and makes debugging a nightmare. Rate-limit instead.
        ip protocol icmp limit rate 10/second accept
        ip6 nexthdr icmpv6 limit rate 10/second accept

        # Drop sshguard-banned IPs before anything else
        ip saddr @sshguard4 drop
        ip6 saddr @sshguard6 drop

        # SSH — kernel-level rate limiting as a first layer before sshguard.
        # Allows bursts (reconnects) but throttles sustained attempts.
        tcp dport $SSH_PORT ct state new limit rate 10/minute burst 20 packets accept
        tcp dport $SSH_PORT drop

        # HTTP and HTTPS for the mirror
        tcp dport { 80, 443 } accept

        # Drop everything else silently (no REJECT — no info leakage,
        # and REJECT on a public server invites RST floods)
    }

    chain forward {
        # This is not a router
        type filter hook forward priority filter; policy drop;
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
EOF

# Enable and apply
systemctl enable --now nftables
nft -f /etc/nftables.conf
echo "nftables active."

# ── 2. sshguard ───────────────────────────────────────────────────────────────
# sshguard watches auth logs and bans IPs that fail repeatedly.
# It integrates directly with the nftables sets we defined above.

echo "Configuring sshguard..."
cat > /etc/sshguard.conf <<'EOF'
# sshguard configuration

# Log backends to watch
LOGREADER="SYSTEMD"

# Block threshold: ban after accumulating 40 "danger" points.
# A single failed password = 10 pts, so this is ~4 failures.
THRESHOLD=40

# How long (seconds) to block on first offense: 120s = 2 minutes.
# Subsequent offenses: BLOCK_TIME * DETECTION_TIME ^ offense_number
# So offenses escalate: 2m, ~13m, ~1.5h, ~7h, ~2d ...
BLOCK_TIME=120

# How long (seconds) without an attack before the offense counter resets
DETECTION_TIME=1800

# Maximum block time cap (seconds): 24 hours
BLOCK_TIME_MAX=86400

# Backend: use our nftables sets
BACKEND="/usr/lib/sshguard/sshg-fw-nft-sets"

# Whitelist your own IPs here to avoid locking yourself out.
# Add one per line, CIDR notation supported.
# Example: WHITELIST_FILE=/etc/sshguard.whitelist
# WHITELIST_FILE=/etc/sshguard.whitelist
EOF

systemctl enable --now sshguard
echo "sshguard active."

# ── 3. SSH daemon hardening ───────────────────────────────────────────────────
# IMPORTANT: This section assumes you already have key-based SSH access.
# It disables password authentication. If you only have password access,
# add your public key to ~/.ssh/authorized_keys BEFORE running this script
# or you will lock yourself out.

echo "Hardening SSH configuration..."

# Backup original
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak.$(date +%Y%m%d%H%M%S)

cat > /etc/ssh/sshd_config <<EOF
# Hardened sshd_config for Arch mirror server

Port $SSH_PORT
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Host keys
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# Modern crypto only. Remove ancient algorithms that are attack surface.
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Authentication
LoginGraceTime 30
PermitRootLogin no
StrictModes yes
MaxAuthTries 3
MaxSessions 5

# KEY-BASED AUTH ONLY. Password auth is disabled.
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
KbdInteractiveAuthentication no

# Disable unused auth methods
UsePAM yes
GSSAPIAuthentication no
HostbasedAuthentication no

# Forwarding — disabled on a mirror server (not a jump host)
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
PermitTunnel no

# Misc hardening
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/ssh/sftp-server

# Log auth attempts (feeds sshguard)
SyslogFacility AUTH
LogLevel VERBOSE

# Timeout idle sessions after 15 minutes
ClientAliveInterval 300
ClientAliveCountMax 3
EOF

# Validate config before restarting — if this fails, we haven't broken anything yet
sshd -t && systemctl restart sshd && echo "sshd restarted with hardened config." \
    || { echo "ERROR: sshd config validation failed. Check /etc/ssh/sshd_config."; exit 1; }

# ── 4. nginx rate limiting ────────────────────────────────────────────────────
# The mirror serves large files legitimately — we don't want to throttle
# package downloads. Rate limiting targets new *connections*, not transfer speed.
# This protects against someone hammering the server with thousands of
# concurrent connections (accidental or deliberate).

echo "Adding nginx rate limiting..."

# Check if nginx is installed before touching its config
if ! systemctl is-enabled nginx &>/dev/null; then
    echo "WARNING: nginx not enabled, skipping nginx hardening."
else
    cat > /etc/nginx/nginx.conf <<'EOF'
user http;
worker_processes auto;
worker_rlimit_nofile 65535;
pid /run/nginx.pid;

events {
    worker_connections 16384;
    multi_accept on;
    use epoll;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 100000;
    types_hash_max_size 2048;

    open_file_cache max=200000 inactive=20m;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Hide nginx version from error pages and headers
    server_tokens off;

    access_log off;
    error_log /var/log/nginx/error.log crit;

    # Rate limit zone: max 30 new connections/second per IP.
    # This is generous for legitimate mirror clients (pacman makes a handful
    # of requests per update) while blocking connection floods.
    # 10m zone = ~160,000 tracked IPs.
    limit_conn_zone $binary_remote_addr zone=per_ip:10m;
    limit_req_zone $binary_remote_addr zone=req_per_ip:10m rate=30r/s;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;

        root /srv/mirror/archlinux;
        autoindex on;

        # Apply connection and request limits
        limit_conn per_ip 32;        # max 32 simultaneous connections per IP
        limit_req zone=req_per_ip burst=60 nodelay;

        # No rate limit on transfer speed (mirror should be fast)
        location / {
            limit_rate 0;
        }
    }
}
EOF

    nginx -t && systemctl reload nginx && echo "nginx reloaded with rate limiting." \
        || { echo "ERROR: nginx config test failed."; exit 1; }
fi

# ── 5. Automatic security updates ────────────────────────────────────────────
# Arch has no unattended-upgrades equivalent. The pragmatic approach for a
# server is a pacman hook that runs paccache (cleanup) and a weekly
# security-only update via a systemd timer.
# Full automatic upgrades are risky on Arch (rolling release can break things),
# so this just notifies — change ExecStart to run pacman -Syu for full auto.

echo "Setting up security update notifications..."
pacman -S --noconfirm --needed pacman-contrib arch-audit

cat > /etc/systemd/system/arch-security-check.service <<'EOF'
[Unit]
Description=Check for Arch Linux security updates
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
# arch-audit checks packages against the Arch security tracker.
ExecStartPre=/usr/bin/pacman -Sy --noconfirm
ExecStart=/bin/bash -c 'arch-audit -u | systemd-cat -t arch-security-check -p warning'
EOF

cat > /etc/systemd/system/arch-security-check.timer <<'EOF'
[Unit]
Description=Weekly Arch Linux security update check

[Timer]
OnCalendar=weekly
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now arch-security-check.timer

# ── 6. Kernel hardening via sysctl ───────────────────────────────────────────

echo "Applying kernel hardening sysctl..."
cat > /etc/sysctl.d/99-harden.conf <<'EOF'
# ── Network hardening ──────────────────────────────────────────────────────

# Ignore ICMP redirects (prevents MITM via routing manipulation)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Don't send ICMP redirects (not a router)
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Ignore source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Enable reverse path filtering (drop spoofed source IPs)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# SYN flood protection
net.ipv4.tcp_syncookies = 1

# Ignore broadcast pings (smurf attack mitigation)
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Log obviously spoofed/impossible source addresses
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable IP forwarding (not a router)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# ── Kernel hardening ───────────────────────────────────────────────────────

# Restrict dmesg to root (leaks kernel addresses otherwise)
kernel.dmesg_restrict = 1

# Hide kernel pointers in /proc (kptr_restrict=2 hides from all users)
kernel.kptr_restrict = 2

# Restrict ptrace to own processes (mitigates some local exploits)
kernel.yama.ptrace_scope = 1

# Disable magic SysRq (no legitimate use on a server)
kernel.sysrq = 0
EOF

sysctl -p /etc/sysctl.d/99-harden.conf
echo "Kernel hardening applied."

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "========================================================"
echo "   HARDENING COMPLETE"
echo "========================================================"
echo ""
echo "Active protections:"
echo "  [nftables]  Firewall: default DROP, HTTP/HTTPS/SSH open"
echo "              SSH rate-limited to 10 new connections/minute"
echo "  [sshguard]  Bans IPs after ~4 failed SSH attempts"
echo "              Escalating ban duration (2min → 24h max)"
echo "  [sshd]      Password auth disabled, root login disabled"
echo "              Ed25519 + RSA keys only, modern crypto only"
echo "  [nginx]     Rate-limited to 32 connections / 30 req/s per IP"
echo "              server_tokens off (version hidden)"
echo "  [sysctl]    SYN cookies, RP filtering, martian logging,"
echo "              dmesg restrict, kptr_restrict, ptrace scope"
echo ""
echo "IMPORTANT REMINDERS:"
echo "  1. Verify you can still SSH before closing this session."
echo "     Open a second terminal and test: ssh user@$(curl -4s ifconfig.io 2>/dev/null)"
echo ""
echo "  2. If you need to whitelist your own IP from sshguard bans:"
echo "     echo 'your.ip.here' >> /etc/sshguard.whitelist"
echo "     Add: WHITELIST_FILE=/etc/sshguard.whitelist to /etc/sshguard.conf"
echo "     systemctl restart sshguard"
echo ""
echo "  3. Check firewall: nft list ruleset"
echo "  4. Check bans:     sshg-logtail  OR  journalctl -u sshguard"
echo "  5. Check SSH:      journalctl -u sshd | grep Failed"
echo "========================================================"
